sonar.projectKey=devsecopspro250
sonar.organization=devsecopspro250
sonar.host.url=https://sonarcloud.io
# Include all code
sonar.sources=.

# Exclude compiled rules if you don't have .class files
sonar.exclusions=**/*.class
